# Generated by Django 4.2.16 on 2025-06-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50, verbose_name='Nombre del Grupo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('cataloge_render', models.BooleanField(default=True, verbose_name='Renderizar en Catálogo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Grupo de Items',
                'verbose_name_plural': 'Grupos de Items',
                'db_table': 'item_group',
                'ordering': ['group_name'],
            },
        ),
    ]
