sonar.projectKey=DP-API
sonar.projectName=DP-API
sonar.projectVersion=1.0

sonar.sources=products
sonar.tests=products/tests

sonar.exclusions=**/.venv/**,**/__pycache__/**,**/migrations/**,**/tests/**
sonar.test.inclusions=products/tests/**/*.py

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8