from products.application.commands import CreateProductCommand
from products.application.dto import ProductDTO
from products.domain.entities import Product
from products.domain.exceptions import AuditUserNotFound, AuditUserRequired
from products.domain.repositories import Clock, ProductRepository
from pricing.application import CalculateProductPrice
from pricing.domain.repositories import PriceRepository, TransactionManager


class CreateProduct:
    def __init__(
        self,
        repository: ProductRepository,
        price_repository: PriceRepository,
        transaction_manager: TransactionManager,
        clock: Clock,
    ):
        self.repository = repository
        self.price_repository = price_repository
        self.transaction_manager = transaction_manager
        self.clock = clock

    def execute(self, command: CreateProductCommand) -> ProductDTO:
        if not command.created_by:
            raise AuditUserRequired("created_by")
        if not self.repository.user_exists(command.created_by):
            raise AuditUserNotFound("created_by")

        product_values = dict(command.__dict__)
        base_net_amount = product_values.pop("base_net_amount")
        price_configuration = product_values.pop("price_configuration")
        product = Product(
            **product_values,
            price=None,
            base_net_amount=base_net_amount,
            price_configuration=price_configuration,
        )
        # Product SKU is generated by PostgreSQL's product_before_insert trigger.
        # Never allow a caller-provided value to bypass the canonical sequence.
        product.sku = None
        product.is_confirmed = bool(command.is_confirmed)
        now = self.clock.now()
        product.initialize_audit(now, self.clock.format_log_timestamp(now))
        with self.transaction_manager.atomic():
            calculated = CalculateProductPrice(self.price_repository).execute(
                base_net_amount,
                price_configuration,
            )
            price = self.price_repository.create_version(
                components=calculated.components,
                configuration_code=calculated.configuration.code,
                product_code=product.code,
                created_at=now,
                created_by=command.created_by,
            )
            product.link_price(
                price.code,
                calculated.configuration.code,
                calculated.components,
            )
            return ProductDTO.from_entity(self.repository.create(product))
